import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import type { SidebarItemConfig } from '@docusaurus/plugin-content-docs/src/sidebars/types.js';
import typedocSidebar from './docs/api/typedoc-sidebar';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  effecsDocumentation: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutor: [
    {
      type: 'category',
      label: 'Nested',
      items: ['start-group/hello'],
    },
    'start-group/hello',
    {
      type: 'link',
      label: 'API',
      href: '/docs/api'
    },
  ],
  typedocSidebar: [
    ...(typedocSidebar.items as SidebarItemConfig[]),
  ],
};

export default sidebars;
